Fix strawberry-graphql union error.  (#1441)
Strawberry-graphql made a recent change to the way it handles strawberry.union. This change is considered breaking because users who have the latest kedro-viz but haven't updated their strawberry-graphql package will encounter the following error:

TypeError: union() missing 1 required positional argument: 'types'

To fix this we have bumped strawberry-graphql dependency package to be at least version 0.192.